meta_product_name: "Louis Hocquet"
meta_title: "Louis Hocquet - Product Manager et Dévelopeur Web"
meta_description: "Product Manager et Développeur Web, passionné par la création d'applications numériques,
je peux vous aider à développer des produits performants et au plus proche des besoins utilisateur 🚀!"
meta_image: "https://res.cloudinary.com/dsbtmlxg7/image/upload/v1713274149/louishocquet/cover.png" # should exist in `app/assets/images/`
# twitter_account: "@product_twitter_account" # required for Twitter Cards
