meta_product_name: "Louis Hocquet"
meta_title: "Louis Hocquet - Créateur d'applications web"
meta_description: "Développeur web et passionné par la création d'applications performantes et intuitives,
je peux vous aider à booster votre activité sur Internet 🚀"
meta_image: "cover.png" # should exist in `app/assets/images/`
# twitter_account: "@product_twitter_account" # required for Twitter Cards
